FROM julia

ADD README.md Project.toml LICENSE /pkg/
ADD src/ /pkg/src/
ADD bin/fbcmt-compare-frog /usr/bin

RUN julia -e 'import Pkg; Pkg.develop(path="/pkg/"); Pkg.resolve(); Pkg.status(); Pkg.instantiate(); Pkg.precompile()'

ENTRYPOINT fbcmt-compare-frog
