FROM julia

ADD README.md Project.toml LICENSE /pkg/
ADD src/ /pkg/src/
ADD bin/fbcmt-run-frog /usr/bin

RUN julia -e 'import Pkg; Pkg.add(["GLPK", "Tulip", "Clarabel", "OSQP", "Clp"]); Pkg.develop(path="/pkg/"); Pkg.resolve(); Pkg.status(); Pkg.instantiate(); Pkg.precompile()'

ENTRYPOINT fbcmt-run-frog
